string="hello world! hello hello"
print(string)
upper=string.upper()
print(upper)
lower=string.lower()

b=len(string)
print(b)
c=string.count("hello")
print(c)
d=string.replace("hello","hi")
print(d)
x="hi"
y=x.strip()
print("blessie",y,"hudson")
find=string.find("world")
print(find)
ind= string.index("world")
print(ind)
print(string.split())